### ISSUE TITLE
possible to use tor-proxy?

### ISSUE THREAD

**Issue by chrisbward** [cretz/bine#58]
Hi, 

I'm building docker containers, wasn't so keen on having go-libtor embedded, or having alpine's apk install it.

I've created a tor-proxy on the same docker network, and was wondering if it's possible to point to that container?

```
cat docker-compose.yml 
version: "3.3"

services:
  torproxy:
    restart: always
    image: dperson/torproxy:latest
    restart: always
    networks:
        - "net"
    ports:
      - "9050:9050" # Tor proxy
      - "9051:9051" # Tor control port
      - "8118:8118" # Privoxy

networks:
  net:
    external: true
```

Cheers

Chris
